CI/CD: Link up remaining data-passing
Includes several squashed bugfix commits.

diff --git a/.github/workflows/cd_receive_pr_artifact.yml b/.github/workflows/cd_receive_pr_artifact.yml
--- a/.github/workflows/cd_receive_pr_artifact.yml
+++ b/.github/workflows/cd_receive_pr_artifact.yml
@@ -2,8 +2,8 @@
 # However, by limiting deployments to the `/staging/pr` subdirectory via this workflow,
 # we minimize the potential attack surface to a known subset of pages.
 
-name: 'CD: Receive PR build artifact'
-run-name: 'CD: Confirm PR deployment safety'
+name: 'CD: Validate PR build artifact'
+run-name: 'CD: Validate PR build artifact'
 
 on:
   workflow_run:
@@ -17,19 +17,84 @@ jobs:
     permissions:
       contents: read
     outputs:
-      params-id: $PARAMS-ID
-      title-header: ${{ steps.fetch-commit-header.outputs.header }}
-      title-source: ${{ steps.set-deployment-target.outputs.source }}
-      title-dest: ${{ steps.set-deployment-target.outputs.destination }}
+      build-id: ${{ env.BUILD_ID }}
+      metadata-id: ${{ steps.upload-metadata.outputs.artifact-id }}
+      title-source: ${{ env.TITLE_SOURCE }}
+      title-dest: ${{ env.TITLE_DEST }}
+      should-notify: ${{ env.SHOULD_NOTIFY }}
+      target-path: ${{ env.TARGET_PATH }}
+
     steps:
-    - name: Download config payload
+    - name: Download PR CD payload
       uses: actions/download-artifact@v8
       with:
-        artifact-ids: ${{ inputs.config-id }}
-        path: payloads/build_config.json
+        name: pr-cd-payload
+        path: ${{ runner.temp }}/pr_cd_payload.json
+        run-id: ${{ github.event.workflow_run.id }}
+        github-token: ${{ secrets.GITHUB_TOKEN }}
 
-    - name: TODO
-      run: echo TODO
+    - name: Unpack payload inputs
+      id: extract_json
+      run: |
+        payload='${{ runner.temp }}/pr_cd_payload.json'
+        echo "payload_json=$payload" >> $GITHUB_OUTPUT
+    
+    - name: Parse payload inputs
+      run: |
+        echo "BUILD_ID=${{ fromJson(steps.extract_json.outputs.payload_json).deploy_env }}" >> $GITHUB_ENV
+        echo "METADATA_JSON=${{ fromJson(steps.extract_json.outputs.payload_json) }}" >> $GITHUB_ENV
+        echo "TITLE_SOURCE=${{ fromJson(steps.extract_json.outputs.payload_json).title_source }}" >> $GITHUB_ENV
+        echo "TITLE_DEST=${{ fromJson(steps.extract_json.outputs.payload_json).title_dest }}" >> $GITHUB_ENV
+        echo "SHOULD_NOTIFY=${{ fromJson(steps.extract_json.outputs.payload_json).should_notify }}" >> $GITHUB_ENV
+      
+    - name: Validate and save payload metadata
+      env:
+        STAGING_PATH: staging/
+        DEPLOY_ENV: ${{ fromJson(env.METADATA_JSON).deploy_env }}
+        TARGET_REPO: ${{ fromJson(env.METADATA_JSON).target_repo }}
+        TARGET_PATH: ${{ fromJson(env.METADATA_JSON).target_path }}
+        PR_NUMBER: ${{ fromJson(env.METADATA_JSON).pr_number }}
+      # Adjust this workflow run as needed to whitelist permissible conditions
+      run: |
+        echo "Checking payload validity." >> $GITHUB_STEP_SUMMARY
+        echo "WARNING: If this step fails, it may indicate tampering or an attack!\n"
+        echo "" >> $GITHUB_STEP_SUMMARY
+        INT_REGEX='^[0-9]+$'
+        if !["$DEPLOY_ENV" = "pr-staging"]; then
+          echo "Invalid DEPLOY_ENV value '${DEPLOY_ENV}'. Expected 'pr-staging'. Aborting." >> $GITHUB_STEP_SUMMARY
+          exit 1
+        elif !["$TARGET_REPO" = "${{ vars.COMPOSITE_TARGET_REPO }}"]; then
+          echo "Invalid target repo '${DEPLOY_ENV}'. Expected ${{ vars.COMPOSITE_TARGET_REPO }}. Aborting." >> $GITHUB_STEP_SUMMARY
+          exit 1
+        elif !["$PR_NUMBER" =~ "$INT_REGEX"]; then
+          echo "Provided PR number '${PR_NUMBER}' is not a valid integer. Aborting." >> $GITHUB_STEP_SUMMARY
+          exit 1
+        elif !["$STAGING_PATH$PR_NUMBER" = "$TARGET_PATH"]; then
+          echo "Provided target path '${TARGET_PATH}' does not match expected target path '${$STAGING_PATH}{$PR_NUMBER}' Aborting." >> $GITHUB_STEP_SUMMARY
+        fi
+
+        echo "All checks passed! The provided payload is well-formed and being pushed to a valid destination." >> $GITHUB_STEP_SUMMARY
+        echo "Deploy environment: $DEPLOY_ENV" >> $GITHUB_STEP_SUMMARY
+        echo "Target repository: $TARGET_REPO" >> $GITHUB_STEP_SUMMARY
+        echo "Target path: $TARGET_PATH" >> $GITHUB_STEP_SUMMARY
+
+        echo "TARGET_PATH=$TARGET_PATH" >> $GITHUB_ENV
+
+        echo $METADATA_JSON > ${{ runner.temp }}/build_${DEPLOY_ENV}${PR_NUMBER}_metadata.json
+        echo ${{ runner.temp }}/build_${DEPLOY_ENV}${PR_NUMBER}_metadata.json
+
+    # Artifacts can't be reused once downloaded, so we need to upload this again.
+    - name: Upload build metadata artifact
+      id: upload-metadata
+      uses: actions/upload-artifact@v8
+      env:
+        DEPLOY_ENV: ${{ fromJson(env.METADATA_JSON).deploy_env }}
+        PR_NUMBER: ${{ fromJson(env.METADATA_JSON).pr_number }}
+      with:
+        # Artifact name
+        name: build-metadata-${{ env.DEPLOY_ENV }}${{ env.PR_NUMBER }}
+        # A file, directory or wildcard pattern that describes what to upload
+        path: ${{ runner.temp }}/build_${{ env.DEPLOY_ENV }}${{ env.PR_NUMBER }}_metadata.json
 
   call-deployment:
     runs-on: ubuntu-latest
@@ -37,15 +102,15 @@ jobs:
     # TODO: Permissions
     steps:
     - name: Call deployment workflow
-      uses: ./.github/workflows/cd_deploy_composite.yml
+      uses: $/.github/workflows/cd_deploy_composite.yml
       with:
         build-id: ${{ needs.extract-config.outputs.build-id }}
         metadata-id: ${{ needs.extract-config.outputs.metadata-id }}
         title-source: ${{ needs.extract-config.outputs.title-source }}
-        title-header: ${{ needs.extract-config.outputs.title-dest }}
+        title-dest: ${{ needs.extract-config.outputs.title-dest }}
   
   notify:
-    # if: true # TODO
+    if: ${{ needs.extract-config.outputs.should-notify }}
     runs-on: ubuntu-latest
     needs: extract-config
     steps:
@@ -54,8 +119,7 @@ jobs:
       with:
         message: |
           **Staging Preview:**
-          🚀 https://hub.ciroh.org/staging/${{ github.event.number }}
+          🚀 https://hub.ciroh.org/${{ needs.extract-config.outputs.target-path }}
           _Will be live within ~10 minutes of this message_
             
           _Built from commit ${{ github.sha }}_
-        # TODO: Replace these with content from payload
